### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by JoelEadeDesign** [TimBHowe/gravityforms-csv-schedule-export#2]
Hi Tim,

I've installed this plugin on a couple of sites but haven't yet had it run successfully. I checked my cron jobs (through Backup Buddy's Server Tools area) and couldn't see a record relating to a Gravity Forms export. Do I need to create a cron job for it to work?

It would be a huge help to have this plugin working. I'd be happy to contribute to the development of it.

Cheers, Joel

**Comment by TimBHowe** [comment]
Hey @JoelEadeDesign,
Sorry for the delay on the reply. I'm still working on finishing the plugin. As this is a free time project I haven't been able to finish it but hope to have a working version in Jan/Feb of 2016.

Thanks
Tim
