### ISSUE TITLE
Plugin seems to not be working

### ISSUE THREAD

**Issue by LCTMichael** [TimBHowe/gravityforms-csv-schedule-export#3]
Tim"I have uploaded and activated the plugin, and have selected one of our Gravity Forms forms as a test subject, so to speak.
I have that form set for to export every hour by way of your plugin.
However, I have not received any exports from that form in the last 2 hours.
Was there anything other than the instructions you list that needs to be done.

**Comment by lembitk** [comment]
As I was shopping around for something similar: [Bulk Reports and Digests for Gravity Forms](https://github.com/soulseekah/Gravity-Forms-Digest-Bulk-Reports) by @soulseekah. /cc @JoelEadeDesign

**Comment by JoelEadeDesign** [comment]
Thanks Lembit. I gave that one a try too. It sends you a digest but not 
the CSV attachment.

Cheers,

Joel

**Comment by lembitk** [comment]
Thanks Joel, this is obviously good to know. 

PS. You might want to consider [filing an issue](https://github.com/soulseekah/Gravity-Forms-Digest-Bulk-Reports/issues/new), so @soulseekah could look into it…

**Comment by JoelEadeDesign** [comment]
Thanks mate. Will do :)

Joel

**Comment by soulseekah** [comment]
@JoelEadeDesign have you defined `GF_DIGESTS_AS_CSV` in wp-config.php?

`define('GF_DIGESTS_AS_CSV', true);`

See: https://github.com/soulseekah/Gravity-Forms-Digest-Bulk-Reports/blob/master/gravityforms-digest/gravityforms-digest.php#L364

**Comment by JoelEadeDesign** [comment]
No, @soulseekah, I hadn't. Thanks for the guidance! :+1:
